//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynovysWebServiceTransitional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public string Username { get; set; }
        public string Fullname { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public System.DateTime LastChangedPass { get; set; }
        public System.DateTime RegisteredOn { get; set; }
        public byte IsActive { get; set; }
    }
}
