//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletLog
    {
        public int ID { get; set; }
        public int Wallet { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Comment { get; set; }
        public int Amount { get; set; }
        public string Action { get; set; }
        public string OwnerID { get; set; }
        public string ReferenceType { get; set; }
        public string ReferenceNumber { get; set; }
    
        public virtual User User { get; set; }
        public virtual Wallet Wallet1 { get; set; }
    }
}
